import { useEffect } from 'react'
import { abbreviationLesson as lesson, clinicDirections, conditionEntries, medicationFrequencies, medicationRoutes, procedureEntries, speciesGroups } from '../content/clinicAbbreviations.js'
import { course } from '../content/curriculum.js'
import { useProgress } from '../context/progress-context.js'
import { Icon } from '../components/Icon.jsx'
import { Breadcrumbs, ButtonLink, PageIntro, Pill } from '../components/PageElements.jsx'

function entryContext(entry) {
  if (!entry.plain) return entry.note
  if (!entry.note) return entry.plain
  const separator = /[.!?]$/.test(entry.plain) ? ' ' : '. '
  return `${entry.plain}${separator}${entry.note}`
}

function GlossaryList({ entries }) {
  return <dl className="clinic-glossary-list">{entries.map((entry) => <div key={entry.abbreviation}><dt>{entry.abbreviation}</dt><dd><strong>{entry.meaning}</strong><span>{entryContext(entry)}</span></dd></div>)}</dl>
}

export function ClinicAbbreviationsLessonPage() {
  const { startLesson } = useProgress()
  useEffect(() => { startLesson(lesson.id, `/lessons/${lesson.id}`, lesson.title) }, [startLesson])

  return <div className="page-container lesson-page"><Breadcrumbs items={[{ label: 'Dashboard', to: '/' }, { label: course.title, to: `/courses/${course.id}` }, { label: lesson.title }]} /><div className="lesson-layout"><article className="lesson-content clinic-abbreviation-lesson">
    <PageIntro eyebrow={lesson.eyebrow} title={lesson.title} description={lesson.summary}><div className="lesson-meta"><span><Icon name="clock" size={18} /> {lesson.estimatedMinutes} minutes</span><Pill tone="orange">{lesson.riskLevel}</Pill><Pill tone="blue">SVC internal language</Pill></div></PageIntro>
    <section className="objective-panel" aria-labelledby="abbreviation-objectives-heading"><div className="objective-panel__icon"><Icon name="target" size={28} /></div><div><p className="card-kicker">By the end</p><h2 id="abbreviation-objectives-heading">Learning objectives</h2><ul className="check-list">{lesson.objectives.map((objective) => <li key={objective}><Icon name="check" size={18} /><span>{objective}</span></li>)}</ul></div></section>

    <section className="lesson-section" id="internal-rule"><p className="eyebrow">Start with safety</p><h2>Recognize it internally—write it out externally</h2><p>Abbreviations save time only inside a shared system where everyone understands the same meaning. Once instructions leave that system, complete wording protects the patient.</p><aside className="internal-safety-panel"><div className="internal-safety-panel__icon"><Icon name="shield" size={28} /></div><div><p className="card-kicker">{lesson.internalRule.title}</p><h3>Prescriptions must use complete instructions.</h3><p>{lesson.internalRule.text}</p><ul>{lesson.internalRule.checklist.map((item) => <li key={item}><Icon name="check" size={17} /> {item}</li>)}</ul></div></aside><div className="three-step-rule"><article><span>01</span><h3>Recognize it</h3><p>What does the abbreviation mean at SVC?</p></article><article><span>02</span><h3>Check the context</h3><p>Is it a route, frequency, test, procedure, condition, or vaccine?</p></article><article><span>03</span><h3>Translate it</h3><p>Can you explain it clearly without using the abbreviation?</p></article></div></section>

    <section className="lesson-section" id="routes"><p className="eyebrow">Medication routes</p><h2>How does it enter the patient?</h2><p>These route abbreviations may appear in SVC’s internal records. Prescriptions, labels, pharmacy communications, and client directions must write the route in full.</p><GlossaryList entries={medicationRoutes} /><div className="internal-external-example"><div><span>Internal record shorthand</span><p>Give 1 tablet PO.</p></div><strong aria-hidden="true">→</strong><div><span>Client-facing wording</span><p>Give one tablet by mouth.</p></div></div></section>

    <section className="lesson-section" id="frequencies"><p className="eyebrow">Frequency and directions</p><h2>Read the abbreviation—then write the complete instruction</h2><p>Frequency is a medication-safety detail. Similar abbreviations can be misread, especially when a prescription is handled outside the veterinary clinic.</p><GlossaryList entries={medicationFrequencies} /><h3 className="subsection-title">Other clinic directions</h3><GlossaryList entries={clinicDirections} /><aside className="fasting-panel"><Icon name="notes" size={23} /><div><strong>NPO needs actual instructions</strong><p>NPO literally means nothing by mouth. Always clarify when food should be removed, whether water is permitted, whether medications should be given, and when normal feeding may resume.</p></div></aside><div className="prescription-compare"><header><Icon name="shield" size={20} /><strong>Medication-safety translation</strong></header><div><section><span>Internal record</span><p>Medication PO BID.</p></section><section><span>Prescription or label</span><p>Give the prescribed medication by mouth twice daily.</p></section></div></div></section>

    <section className="lesson-section" id="procedures"><p className="eyebrow">Procedures and diagnostics</p><h2>Know what kind of action is being described</h2><p>Context helps distinguish a measurement, laboratory test, procedure, fluid, or patient status.</p><GlossaryList entries={procedureEntries} /></section>

    <section className="lesson-section" id="conditions"><p className="eyebrow">Conditions and context</p><h2>Recognize the term without turning it into a diagnosis</h2><p>An abbreviation may name a condition, but using the abbreviation does not establish that the patient has that condition.</p><GlossaryList entries={conditionEntries} /><div className="context-callouts"><article><p className="card-kicker">Historical terminology</p><h3>HGE and AHDS</h3><p>HGE may appear in older records or internal SVC records. Acute hemorrhagic diarrhea syndrome, or AHDS, is the current term commonly used for this syndrome.</p></article><article><p className="card-kicker">Informal shorthand</p><h3>ADR is not a diagnosis</h3><p>“Ain’t doing right” signals a vague concern. Document the specific history, timeline, and observations that are known.</p></article></div></section>

    <section className="lesson-section" id="species"><p className="eyebrow">Species terminology</p><h2>Use the patient and clinic context</h2><p>These groups include disease, testing, and preventive-care shorthand from the SVC reference. Product components and naming can vary, so verify the product and medical record.</p><div className="species-abbreviation-stack">{speciesGroups.map((group) => <article key={group.title}><header><h3>{group.title}</h3><span>{group.entries.length} terms</span></header><dl>{group.entries.map((entry) => <div key={entry.abbreviation}><dt>{entry.abbreviation}</dt><dd><strong>{entry.meaning}</strong><span>{entryContext(entry)}</span></dd></div>)}</dl></article>)}</div></section>

    <section className="lesson-section" id="translations"><p className="eyebrow">Translate the shorthand</p><h2>Say what the record means</h2><div className="abbreviation-translation-stack">{lesson.translations.map((item) => <article key={item.title}><header><p className="card-kicker">Applied example</p><h3>{item.title}</h3></header><div><section><span>Internal shorthand</span><p>{item.internal}</p></section><strong aria-hidden="true">→</strong><section><span>Complete wording</span><p>{item.external}</p></section></div><aside><strong>Why this works:</strong> {item.why}</aside></article>)}</div><aside className="closing-safety-rule"><Icon name="shield" size={24} /><p><strong>Remember:</strong> Abbreviations save time inside a shared system. Complete wording protects the patient whenever instructions leave that system.</p></aside></section>

    <section className="source-panel" id="abbreviation-sources"><div className="source-panel__heading"><div><p className="eyebrow">Content trust</p><h2>Sources and review</h2></div><Pill tone="blue">{lesson.reviewStatus}</Pill></div><dl className="review-details"><div><dt>Last reviewed</dt><dd>{lesson.reviewedAt}</dd></div><div><dt>Review type</dt><dd>{lesson.reviewerRole}</dd></div><div><dt>Scope</dt><dd>{lesson.species.join(' · ')}</dd></div></dl><ul className="source-list">{lesson.sources.map((source) => <li key={source.title}>{source.url ? <a href={source.url} target="_blank" rel="noreferrer">{source.title}</a> : <strong>{source.title}</strong>}<span>{source.organization}</span><p>{source.note}</p></li>)}</ul></section>
    <div className="lesson-next"><div><p className="card-kicker">Ready to practice?</p><h2>Translate the SVC shorthand.</h2><p>Five questions about routes, medication safety, diagnostics, and context-dependent abbreviations.</p></div><ButtonLink to={`/lessons/${lesson.id}/quiz`}>Start knowledge check</ButtonLink></div>
  </article><aside className="lesson-sidebar" aria-label="Lesson contents"><p className="card-kicker">In this lesson</p><ol><li><a href="#internal-rule"><span>01</span>Internal-use rule</a></li><li><a href="#routes"><span>02</span>Routes</a></li><li><a href="#frequencies"><span>03</span>Frequency</a></li><li><a href="#procedures"><span>04</span>Procedures</a></li><li><a href="#conditions"><span>05</span>Conditions</a></li><li><a href="#species"><span>06</span>Species terms</a></li><li><a href="#translations"><span>07</span>Translation</a></li></ol><ButtonLink to={`/lessons/${lesson.id}/reference`} variant="quiet">Search all abbreviations</ButtonLink></aside></div></div>
}
