import { useEffect } from 'react'
import { lesson } from '../content/curriculum.js'
import { useProgress } from '../context/progress-context.js'
import { Icon } from '../components/Icon.jsx'
import { Breadcrumbs, ButtonLink, PageIntro, Pill } from '../components/PageElements.jsx'

export function LessonPage() {
  const { startLesson } = useProgress()
  useEffect(() => { startLesson(lesson.id, `/lessons/${lesson.id}`, lesson.title) }, [startLesson])
  return <div className="page-container lesson-page"><Breadcrumbs items={[{ label: 'Dashboard', to: '/' }, { label: 'Medical Terminology', to: '/courses/medical-terminology' }, { label: lesson.title }]} /><div className="lesson-layout"><article className="lesson-content">
    <PageIntro eyebrow={lesson.eyebrow} title={lesson.title} description={lesson.summary}><div className="lesson-meta"><span><Icon name="clock" size={18} /> {lesson.estimatedMinutes} minutes</span><Pill tone="orange">{lesson.riskLevel}</Pill><Pill tone="blue">{lesson.species[0]}</Pill></div></PageIntro>
    <section className="objective-panel" aria-labelledby="objectives-heading"><div className="objective-panel__icon"><Icon name="target" size={28} /></div><div><p className="card-kicker">By the end</p><h2 id="objectives-heading">Learning objectives</h2><ul className="check-list">{lesson.objectives.map((objective) => <li key={objective}><Icon name="check" size={18} /><span>{objective}</span></li>)}</ul></div></section>
    {lesson.sections.map((section) => <section className="lesson-section" id={section.id} key={section.id}><p className="eyebrow">{section.kicker}</p><h2>{section.title}</h2>{section.paragraphs?.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.terms && <div className="term-grid">{section.terms.map((item) => <article className="term-card" key={item.term}><h3>{item.term}</h3><p>{item.definition}</p><span>{item.cue}</span></article>)}</div>}{section.example && <div className="example-box"><span>Example</span><p>{section.example}</p></div>}{section.callout && <aside className="lesson-callout"><Icon name="spark" size={22} /><div><strong>{section.callout.label}</strong><p>{section.callout.text}</p></div></aside>}</section>)}
    <section className="scenario-card"><p className="eyebrow">Applied example</p><h2>{lesson.scenario.title}</h2><p>{lesson.scenario.prompt}</p><div><strong>Clear, neutral description</strong><p>{lesson.scenario.note}</p></div></section>
    <section className="documentation-example" id="documentation-example"><div className="documentation-example__heading"><p className="eyebrow">Clinical translation</p><h2>{lesson.documentationExample.title}</h2><p>Here is how the same fictional rabbit finding moves from everyday wording into precise, objective documentation.</p></div><div className="plain-language-card"><span>Everyday description</span><p>{lesson.documentationExample.plainLanguage}</p></div><div className="term-translation" aria-label="Everyday words translated into anatomical terms">{lesson.documentationExample.termMap.map(([plain, clinical]) => <div key={plain}><span>{plain}</span><strong aria-hidden="true">→</strong><span>{clinical}</span></div>)}</div><div className="exam-note-card"><div className="exam-note-card__top"><span>Example exam-form entry</span><strong>Fictional patient · Rabbit</strong></div><dl>{lesson.documentationExample.examNote.map((item) => <div key={item.label}><dt>{item.label}</dt><dd>{item.text}</dd></div>)}</dl></div><aside className="documentation-caution"><Icon name="shield" size={22} /><div><strong>Stay objective</strong><p>{lesson.documentationExample.caution}</p></div></aside></section>
    <section className="source-panel" id="lesson-sources"><div className="source-panel__heading"><div><p className="eyebrow">Content trust</p><h2>Sources and review</h2></div><Pill tone="blue">{lesson.reviewStatus}</Pill></div><dl className="review-details"><div><dt>Last reviewed</dt><dd>{lesson.reviewedAt}</dd></div><div><dt>Review type</dt><dd>{lesson.reviewerRole}</dd></div><div><dt>Scope</dt><dd>{lesson.species.join(' · ')}</dd></div></dl><ul className="source-list">{lesson.sources.map((source) => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.title}</a><span>{source.organization}</span><p>{source.note}</p></li>)}</ul></section>
    <div className="lesson-next"><div><p className="card-kicker">Ready to practice?</p><h2>Check what stuck.</h2><p>Five questions, each with an explanation. Your score is for review—not proof of clinical competency.</p></div><ButtonLink to={`/lessons/${lesson.id}/quiz`}>Start knowledge check</ButtonLink></div>
  </article><aside className="lesson-sidebar" aria-label="Lesson contents"><p className="card-kicker">In this lesson</p><ol>{lesson.sections.map((section, index) => <li key={section.id}><a href={`#${section.id}`}><span>0{index + 1}</span>{section.title}</a></li>)}<li><a href="#documentation-example"><span>07</span>Exam-form example</a></li><li><a href="#lesson-sources"><span>08</span>Sources & review</a></li></ol><ButtonLink to={`/lessons/${lesson.id}/reference`} variant="quiet">Open reference card</ButtonLink></aside></div></div>
}
