import { useEffect } from 'react'
import { medicalRecordLesson as lesson } from '../content/medicalRecord.js'
import { course } from '../content/curriculum.js'
import { useProgress } from '../context/progress-context.js'
import { Icon } from '../components/Icon.jsx'
import { Breadcrumbs, ButtonLink, PageIntro, Pill } from '../components/PageElements.jsx'

function SoapSection({ section }) {
  return <article className={`soap-section soap-section--${section.tone}`}><header><span className="soap-letter">{section.letter}</span><div><p className="card-kicker">{section.question}</p><h3>{section.title}</h3></div><Pill tone={section.tone}>{section.owner}</Pill></header><p>{section.description}</p><div className="memory-cue"><Icon name="spark" size={19} /><span><strong>Think:</strong> {section.cue}</span></div>{section.clientWords && <div className="soap-translation"><div><span>Everyday wording</span><p>{section.clientWords}</p></div><strong aria-hidden="true">→</strong><div><span>Medical-record wording</span><p>{section.recordWords}</p></div></div>}{section.note && <p className="soap-note">{section.note}</p>}{section.vocabulary && <dl className="assessment-vocabulary">{section.vocabulary.map(([term, meaning]) => <div key={term}><dt>{term}</dt><dd>{meaning}</dd></div>)}</dl>}</article>
}

export function MedicalRecordLessonPage() {
  const { startLesson } = useProgress()
  useEffect(() => { startLesson(lesson.id, `/lessons/${lesson.id}`, lesson.title) }, [startLesson])

  return <div className="page-container lesson-page"><Breadcrumbs items={[{ label: 'Dashboard', to: '/' }, { label: course.title, to: `/courses/${course.id}` }, { label: lesson.title }]} /><div className="lesson-layout"><article className="lesson-content record-language-lesson">
    <PageIntro eyebrow={lesson.eyebrow} title={lesson.title} description={lesson.summary}><div className="lesson-meta"><span><Icon name="clock" size={18} /> {lesson.estimatedMinutes} minutes</span><Pill tone="orange">{lesson.riskLevel}</Pill><Pill tone="blue">SVC records</Pill></div></PageIntro>
    <section className="objective-panel" aria-labelledby="record-objectives-heading"><div className="objective-panel__icon"><Icon name="target" size={28} /></div><div><p className="card-kicker">By the end</p><h2 id="record-objectives-heading">Learning objectives</h2><ul className="check-list">{lesson.objectives.map((objective) => <li key={objective}><Icon name="check" size={18} /><span>{objective}</span></li>)}</ul></div></section>

    <section className="lesson-section" id="record-purpose"><p className="eyebrow">Start here</p><h2>A shared language protects the story of the visit</h2><p>A veterinary medical record is a legal document. It should let someone unfamiliar with the patient understand the visit without relying on memory or assumptions.</p><div className="record-purpose-grid">{lesson.recordPurpose.map((item) => <div key={item}><Icon name="check" size={18} /><span>{item}</span></div>)}</div><aside className="lesson-callout"><Icon name="shield" size={22} /><div><strong>This lesson teaches the language</strong><p>The Patient Intake & TPR course will teach how to collect and hand off this information during an appointment.</p></div></aside></section>

    <section className="lesson-section" id="soap"><p className="eyebrow">The record structure</p><h2>SOAP answers four different questions</h2><p>Each section has a distinct purpose. Keeping information in the correct section makes the record easier to understand.</p><div className="soap-stack">{lesson.soapSections.map((section) => <SoapSection section={section} key={section.letter} />)}</div></section>

    <section className="lesson-section" id="record-terms"><p className="eyebrow">Core vocabulary</p><h2>Common medical-record terms</h2><div className="record-term-grid">{lesson.recordTerms.map((item) => <article key={item.term}><h3>{item.term}</h3><p>{item.definition}</p><div><span>Example</span><p>{item.example}</p></div></article>)}</div></section>

    <section className="lesson-section" id="abbreviations"><p className="eyebrow">SVC shorthand</p><h2>Common intake abbreviations</h2><p>Abbreviations save space only when everyone understands the same meaning.</p><div className="abbreviation-grid">{lesson.abbreviations.map((item) => <article key={item.term}><strong>{item.term}</strong><div><h3>{item.means}</h3><p>{item.note}</p></div></article>)}</div><div className="preventive-panel"><p className="card-kicker">UTD needs a source</p><h3>“Up to date” is not complete by itself</h3><dl>{lesson.preventiveStatuses.map(([status, meaning]) => <div key={status}><dt>{status}</dt><dd>{meaning}</dd></div>)}</dl></div></section>

    <section className="lesson-section" id="accuracy"><p className="eyebrow">Accurate uncertainty</p><h2>Choose the word that matches what is known</h2><p>Accurate uncertainty is more useful than making the record appear complete.</p><div className="accuracy-language-grid">{lesson.accuracyTerms.map((item) => <article key={item.term}><h3>{item.term}</h3><p>{item.meaning}</p><div><span>Example</span><p>{item.example}</p></div></article>)}</div></section>

    <section className="lesson-section" id="translations"><p className="eyebrow">Clinical translation</p><h2>From client wording to record wording</h2><div className="translation-stack">{lesson.translations.map((item) => <article key={item.title}><header><p className="card-kicker">Applied example</p><h3>{item.title}</h3></header><div className="translation-compare"><div><span>Client wording</span><blockquote>{item.client}</blockquote></div><div><span>Medical-record wording</span><blockquote>{item.record}</blockquote></div></div>{item.map && <div className="word-map">{item.map.map(([plain, record]) => <div key={plain}><span>{plain}</span><strong aria-hidden="true">→</strong><span>{record}</span></div>)}</div>}{item.why && <p className="translation-why"><strong>Why this is clearer:</strong> {item.why}</p>}</article>)}</div></section>

    <section className="lesson-section" id="bella-soap"><p className="eyebrow">Put the structure together</p><h2>One patient across the SOAP</h2><p>The same patient appears throughout the record, but every section serves a different purpose.</p><div className="bella-soap"><div className="patient-banner"><Icon name="notes" size={24} /><strong>Bella · 5-year-old spayed female Labrador retriever</strong></div><dl>{lesson.bellaSoap.map(([label, text]) => <div key={label}><dt>{label}</dt><dd>{text}</dd></div>)}</dl></div></section>

    <section className="source-panel" id="record-sources"><div className="source-panel__heading"><div><p className="eyebrow">Content trust</p><h2>Sources and review</h2></div><Pill tone="blue">{lesson.reviewStatus}</Pill></div><dl className="review-details"><div><dt>Last reviewed</dt><dd>{lesson.reviewedAt}</dd></div><div><dt>Review type</dt><dd>{lesson.reviewerRole}</dd></div><div><dt>Scope</dt><dd>{lesson.species.join(' · ')}</dd></div></dl><ul className="source-list">{lesson.sources.map((source) => <li key={source.title}>{source.url ? <a href={source.url} target="_blank" rel="noreferrer">{source.title}</a> : <strong>{source.title}</strong>}<span>{source.organization}</span><p>{source.note}</p></li>)}</ul></section>
    <div className="lesson-next"><div><p className="card-kicker">Ready to practice?</p><h2>Check your record-language skills.</h2><p>Five questions about SOAP, SVC responsibility, and accurate documentation language.</p></div><ButtonLink to={`/lessons/${lesson.id}/quiz`}>Start knowledge check</ButtonLink></div>
  </article><aside className="lesson-sidebar" aria-label="Lesson contents"><p className="card-kicker">In this lesson</p><ol><li><a href="#record-purpose"><span>01</span>Why language matters</a></li><li><a href="#soap"><span>02</span>SOAP</a></li><li><a href="#record-terms"><span>03</span>Record terms</a></li><li><a href="#abbreviations"><span>04</span>Abbreviations</a></li><li><a href="#accuracy"><span>05</span>Accuracy words</a></li><li><a href="#translations"><span>06</span>Clinical translation</a></li><li><a href="#bella-soap"><span>07</span>Bella’s SOAP</a></li><li><a href="#record-sources"><span>08</span>Sources & review</a></li></ol><ButtonLink to={`/lessons/${lesson.id}/reference`} variant="quiet">Open reference card</ButtonLink></aside></div></div>
}
