import { useState } from 'react'
import { lesson } from '../content/curriculum.js'
import { useProgress } from '../context/progress-context.js'
import { ButtonLink, PageIntro, Pill, ProgressBar } from '../components/PageElements.jsx'

export function ProgressPage() {
  const { progress, reset } = useProgress(), [confirming, setConfirming] = useState(false), saved = progress.lessons[lesson.id], percentage = saved?.complete ? 100 : saved?.started ? 35 : 0
  return <div className="page-container page-stack"><PageIntro eyebrow="Saved on this device" title="My progress" description="Your study history is stored in this browser only. It does not contain patient or client information and does not sync between devices." /><section className="progress-dashboard"><article className="progress-stat"><span>Lessons completed</span><strong>{saved?.complete ? 1 : 0}</strong><small>of 1 available</small></article><article className="progress-stat"><span>Best quiz score</span><strong>{saved?.bestScore ?? '—'}{saved?.bestScore !== undefined ? '%' : ''}</strong><small>{saved?.attempts ? `${saved.attempts} attempt${saved.attempts === 1 ? '' : 's'}` : 'No attempts yet'}</small></article><article className="progress-stat"><span>Review concepts</span><strong>{saved?.missedConcepts?.length ?? 0}</strong><small>from latest attempt</small></article></section><section className="saved-course-card"><div><p className="card-kicker">Medical Terminology</p><h2>{lesson.title}</h2><ProgressBar value={percentage} label="Lesson progress" /></div><div><Pill tone={saved?.complete ? 'blue' : 'neutral'}>{saved?.complete ? 'Complete' : saved?.started ? 'In progress' : 'Not started'}</Pill><ButtonLink to={`/lessons/${lesson.id}`} variant="secondary">{saved?.started ? 'Open lesson' : 'Start lesson'}</ButtonLink></div></section><section className="data-panel"><div><p className="eyebrow">Local data</p><h2>Reset learning progress</h2><p>This removes only Vet Tech Learning progress from this browser. It cannot be undone.</p></div>{!confirming ? <button className="button button--danger" type="button" onClick={() => setConfirming(true)}>Reset progress</button> : <div className="confirm-reset" role="group" aria-label="Confirm progress reset"><strong>Remove all saved progress?</strong><div><button className="button button--danger" type="button" onClick={() => { reset(); setConfirming(false) }}>Yes, reset</button><button className="button button--quiet" type="button" onClick={() => setConfirming(false)}>Cancel</button></div></div>}</section></div>
}
