import { useState } from 'react'
import { Link } from 'react-router'
import { lesson } from '../content/curriculum.js'
import { scoreQuiz } from '../domain/quiz.js'
import { useProgress } from '../context/progress-context.js'
import { Icon } from '../components/Icon.jsx'
import { Breadcrumbs, ButtonLink, Pill, ProgressBar } from '../components/PageElements.jsx'

export function QuizPage() {
  const [index, setIndex] = useState(0), [selected, setSelected] = useState(''), [answers, setAnswers] = useState({}), [checked, setChecked] = useState(false), [result, setResult] = useState(null)
  const { recordQuiz } = useProgress(), question = lesson.questions[index], isCorrect = selected === question?.correctAnswer
  function checkAnswer(event) { event.preventDefault(); if (!selected) return; setAnswers((current) => ({ ...current, [question.id]: selected })); setChecked(true) }
  function nextQuestion() { const nextAnswers = { ...answers, [question.id]: selected }; if (index === lesson.questions.length - 1) { const quizResult = scoreQuiz(lesson.questions, nextAnswers); recordQuiz(lesson.id, quizResult); setResult(quizResult); return } setIndex((current) => current + 1); setSelected(''); setChecked(false) }
  function retry() { setIndex(0); setSelected(''); setAnswers({}); setChecked(false); setResult(null) }
  if (result) return <div className="page-container quiz-page"><div className="quiz-summary"><span className="summary-mark"><Icon name="check" size={36} /></span><Pill tone="orange">Knowledge check complete</Pill><h1>{result.percentage}%</h1><p className="summary-lead">You answered {result.correctCount} of {result.total} correctly.</p><p>Completion records exposure to the lesson. Your score simply helps choose what to review next.</p>{result.missedConcepts.length > 0 ? <div className="review-needed"><strong>Review these concepts</strong><ul>{result.missedConcepts.map((concept) => <li key={concept}>{concept}</li>)}</ul></div> : <div className="review-needed review-needed--clear"><strong>Nothing missed this round.</strong><p>Nice work—use the reference card for quick recall later.</p></div>}<div className="button-row"><ButtonLink to={`/lessons/${lesson.id}/reference`}>Open reference card</ButtonLink><button className="button button--secondary" type="button" onClick={retry}>Try again</button></div><Link className="text-link" to="/">Return to dashboard</Link></div></div>
  return <div className="page-container quiz-page"><Breadcrumbs items={[{ label: 'Lesson', to: `/lessons/${lesson.id}` }, { label: 'Knowledge check' }]} /><header className="quiz-header"><div><p className="eyebrow">Knowledge check</p><h1>Make the terms stick</h1></div><Pill tone="blue">Question {index + 1} of {lesson.questions.length}</Pill></header><ProgressBar value={Math.round(((index + (checked ? 1 : 0)) / lesson.questions.length) * 100)} label="Quiz progress" />
    <form className="question-card" onSubmit={checkAnswer}><fieldset disabled={checked}><legend>{question.prompt}</legend><div className="answer-list">{question.options.map((option) => { const optionCorrect = checked && option === question.correctAnswer, optionIncorrect = checked && option === selected && !isCorrect; return <label className={`answer-option${optionCorrect ? ' is-correct' : ''}${optionIncorrect ? ' is-incorrect' : ''}`} key={option}><input type="radio" name="answer" value={option} checked={selected === option} onChange={(event) => setSelected(event.target.value)} /><span className="radio-mark" /><span>{option}</span>{optionCorrect && <strong>Correct</strong>}{optionIncorrect && <strong>Selected</strong>}</label> })}</div></fieldset>
      {checked && <div className={isCorrect ? 'feedback feedback--correct' : 'feedback feedback--incorrect'} role="status"><Icon name={isCorrect ? 'check' : 'book'} size={24} /><div><strong>{isCorrect ? 'That’s right.' : 'Not quite—use the relationship.'}</strong><p>{question.explanation}</p></div></div>}
      <div className="question-actions">{!checked ? <button className="button button--primary" type="submit" disabled={!selected}>Check answer <Icon name="arrow" size={18} /></button> : <button className="button button--primary" type="button" onClick={nextQuestion}>{index === lesson.questions.length - 1 ? 'See results' : 'Next question'} <Icon name="arrow" size={18} /></button>}</div>
    </form></div>
}
