import { lesson } from '../content/curriculum.js'
import { useProgress } from '../context/progress-context.js'
import { ButtonLink, PageIntro, Pill } from '../components/PageElements.jsx'
import { Icon } from '../components/Icon.jsx'

export function ReviewPage() {
  const { progress } = useProgress(), saved = progress.lessons[lesson.id], missed = saved?.missedConcepts ?? []
  return <div className="page-container page-stack"><PageIntro eyebrow="Focused review" title="Practice what needs another look" description="Missed concepts appear here after a knowledge check. Review is separate from your original attempt." />{missed.length > 0 ? <section className="review-list" aria-labelledby="review-heading"><div className="section-heading section-heading--split compact-heading"><div><p className="eyebrow">From your latest attempt</p><h2 id="review-heading">{missed.length} concept{missed.length === 1 ? '' : 's'} to revisit</h2></div><Pill tone="orange">Best score {saved.bestScore}%</Pill></div>{missed.map((concept, index) => <article className="review-row" key={concept}><span>0{index + 1}</span><div><h3>{concept}</h3><p>Revisit the paired terms and their reference points, then try the knowledge check again.</p></div></article>)}<div className="button-row"><ButtonLink to={`/lessons/${lesson.id}/reference`}>Open reference card</ButtonLink><ButtonLink to={`/lessons/${lesson.id}/quiz`} variant="secondary">Retry quiz</ButtonLink></div></section> : <section className="empty-state"><span><Icon name="book" size={34} /></span><h2>{saved?.complete ? 'Nothing is waiting for review.' : 'Your review queue is empty.'}</h2><p>{saved?.complete ? 'You cleared every concept on your latest attempt.' : 'Complete the first knowledge check and any missed concepts will appear here.'}</p><ButtonLink to={saved?.complete ? `/lessons/${lesson.id}/reference` : `/lessons/${lesson.id}`}>{saved?.complete ? 'Open reference card' : 'Start the first lesson'}</ButtonLink></section>}</div>
}
