import { useEffect } from 'react'
import { wordBuildingLesson as lesson } from '../content/wordBuilding.js'
import { course } from '../content/curriculum.js'
import { useProgress } from '../context/progress-context.js'
import { Icon } from '../components/Icon.jsx'
import { Breadcrumbs, ButtonLink, PageIntro, Pill } from '../components/PageElements.jsx'

function TermTable({ headings, rows }) {
  return <div className="word-table-wrap"><table className="word-table"><thead><tr>{headings.map((heading) => <th key={heading}>{heading}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.join('-')}>{row.map((cell, index) => index === 0 ? <th key={cell}>{cell}</th> : <td key={cell}>{cell}</td>)}</tr>)}</tbody></table></div>
}

function PieceMap({ pieces }) {
  return <div className="piece-map">{pieces.map(([piece, meaning]) => <div key={piece}><strong>{piece}</strong><span>{meaning}</span></div>)}</div>
}

function Pronunciation({ children }) {
  return <p className="pronunciation"><span>Pronounced</span> {children}</p>
}

export function WordBuildingLessonPage() {
  const { startLesson } = useProgress()
  useEffect(() => { startLesson(lesson.id, `/lessons/${lesson.id}`, lesson.title) }, [startLesson])

  return <div className="page-container lesson-page"><Breadcrumbs items={[{ label: 'Dashboard', to: '/' }, { label: course.title, to: `/courses/${course.id}` }, { label: lesson.title }]} /><div className="lesson-layout"><article className="lesson-content word-building-lesson">
    <PageIntro eyebrow={lesson.eyebrow} title={lesson.title} description={lesson.summary}><div className="lesson-meta"><span><Icon name="clock" size={18} /> {lesson.estimatedMinutes} minutes</span><Pill tone="orange">{lesson.riskLevel}</Pill><Pill tone="blue">SVC examples</Pill></div></PageIntro>
    <section className="objective-panel" aria-labelledby="word-objectives-heading"><div className="objective-panel__icon"><Icon name="target" size={28} /></div><div><p className="card-kicker">By the end</p><h2 id="word-objectives-heading">Learning objectives</h2><ul className="check-list">{lesson.objectives.map((objective) => <li key={objective}><Icon name="check" size={18} /><span>{objective}</span></li>)}</ul></div></section>

    <section className="lesson-section" id="word-parts"><p className="eyebrow">Start here</p><h2>Medical words are puzzles</h2><p>Long medical words can feel intimidating, but many are assembled from smaller pieces. Not every term contains all three pieces; some contain only a root and suffix, while others combine multiple roots.</p><div className="word-part-grid">{lesson.wordParts.map((part) => <article key={part.name}><span>{part.position}</span><h3>{part.name}</h3><p>{part.description}</p><div><strong>Example</strong><p>{part.example}</p></div></article>)}</div></section>

    <section className="lesson-section" id="combining-vowels"><p className="eyebrow">Connect the pieces</p><h2>Meet the combining vowel</h2><p>A root is sometimes joined with a vowel—most often <strong>o</strong>—to make a medical term easier to pronounce. The vowel connects the parts but has no medical meaning of its own.</p><div className="equation-card"><span>cardi</span><strong>+</strong><span>o</span><strong>=</strong><span>cardi/o</span></div><div className="combining-grid"><article><p className="card-kicker">The “o” commonly stays</p><h3>Before a consonant</h3><p><strong>cardi/o</strong> + <strong>-logy</strong> = cardiology</p></article><article><p className="card-kicker">The “o” is often dropped</p><h3>Before a vowel</h3><p><strong>gastr/o</strong> + <strong>-itis</strong> = gastritis</p></article></div><aside className="lesson-callout"><Icon name="spark" size={22} /><div><strong>Focus on the meaningful pieces</strong><p>These patterns are helpful, but medical language contains exceptions. You do not need to force every term into exactly three parts.</p></div></aside></section>

    <section className="lesson-section" id="prefixes"><p className="eyebrow">Start with the prefix</p><h2>The beginning changes the meaning</h2><div className="prefix-stack">{lesson.prefixPairs.map((pair) => <article className="prefix-pair" key={pair.title}><header><h3>{pair.title}</h3></header><div className="prefix-term-grid">{pair.terms.map((term) => <div key={term.term}><h4>{term.term}</h4><p>{term.meaning}</p><div className="memory-cue"><Icon name="spark" size={18} /><span><strong>Think:</strong> {term.cue}</span></div><code>{term.example}</code></div>)}</div><div className="prefix-example"><span>Applied example</span><p>{pair.scenario}</p><strong>{pair.wording}</strong>{pair.breakdown && <><PieceMap pieces={pair.breakdown} /><p className="applied-translation"><b>Translation:</b> {pair.translation}</p></>}{pair.pronunciation && <Pronunciation>{pair.pronunciation}</Pronunciation>}<p><b>Why this term?</b> {pair.contrast}</p>{pair.alternative && <div className="alternative-term"><strong>{pair.alternative.term}</strong><span>{pair.alternative.meaning}</span><Pronunciation>{pair.alternative.pronunciation}</Pronunciation></div>}{pair.note && <p className="prefix-note"><b>Important:</b> {pair.note}</p>}</div></article>)}</div><h3 className="subsection-title">Other useful prefixes</h3><TermTable headings={['Word part', 'Meaning', 'Memory association', 'Example']} rows={lesson.otherPrefixes} /></section>

    <section className="lesson-section" id="roots"><p className="eyebrow">Find the root</p><h2>Which structure or system?</h2><p>The root usually tells you which structure, organ, or body system the term concerns.</p><TermTable headings={['Root', 'Meaning', 'Example']} rows={lesson.roots} /></section>

    <section className="lesson-section" id="suffixes"><p className="eyebrow">Read the suffix</p><h2>What kind of condition or procedure?</h2><div className="suffix-stack">{lesson.suffixGroups.map((group) => <article key={group.title}><h3>{group.title}</h3><TermTable headings={['Suffix', 'Meaning', 'Example']} rows={group.items} /></article>)}</div></section>

    <section className="lesson-section" id="svc-shorthand"><p className="eyebrow">Inside SVC shorthand</p><h2>Medication routes make more sense in full</h2><p>Abbreviations are easier to remember when you understand the medical words behind them.</p><div className="route-grid">{lesson.svcRoutes.map((route) => <article key={route.abbreviation}><header><span>{route.abbreviation}</span><div><h3>{route.term}</h3>{route.pronunciation && <Pronunciation>{route.pronunciation}</Pronunciation>}</div></header><PieceMap pieces={route.pieces} /><p>{route.translation}</p></article>)}</div><aside className="contrast-card"><strong>Try the contrast</strong><p>Why is an injection given beneath the skin called <b>subcutaneous</b> rather than <b>intramuscular</b>?</p><p>It is administered under the skin, not within a muscle. If the medication were injected into the muscle, the route would be intramuscular.</p></aside></section>

    <section className="lesson-section" id="word-lab"><p className="eyebrow">Build the meaning</p><h2>Put the pieces to work</h2><div className="word-lab-grid">{lesson.wordLab.map((word) => <article key={word.term}><header><div><h3>{word.term}</h3>{word.pronunciation && <Pronunciation>{word.pronunciation}</Pronunciation>}</div></header><PieceMap pieces={word.pieces} /><div className="literal-translation"><span>Translation</span><p>{word.translation}</p></div>{word.example && <p>{word.example}</p>}{word.contrast && <p><strong>Why this word?</strong> {word.contrast}</p>}</article>)}</div></section>

    <section className="lesson-section" id="limits"><p className="eyebrow">Important limitation</p><h2>Word parts are clues, not a diagnosis</h2><p>Breaking apart a term helps you estimate its general meaning. It does not always provide the complete clinical definition.</p><ul className="limit-list">{lesson.limitations.map((item) => <li key={item}><Icon name="shield" size={20} /><span>{item}</span></li>)}</ul><aside className="lesson-callout"><Icon name="notes" size={22} /><div><strong>Never guess at an unfamiliar term</strong><p>Confirm the intended meaning and follow the veterinarian’s documentation guidance. A matching word breakdown does not turn an observation into a diagnosis.</p></div></aside></section>

    <section className="source-panel" id="word-sources"><div className="source-panel__heading"><div><p className="eyebrow">Content trust</p><h2>Sources and review</h2></div><Pill tone="blue">{lesson.reviewStatus}</Pill></div><dl className="review-details"><div><dt>Last reviewed</dt><dd>{lesson.reviewedAt}</dd></div><div><dt>Review type</dt><dd>{lesson.reviewerRole}</dd></div><div><dt>Scope</dt><dd>{lesson.species.join(' · ')}</dd></div></dl><ul className="source-list">{lesson.sources.map((source) => <li key={source.title}>{source.url ? <a href={source.url} target="_blank" rel="noreferrer">{source.title}</a> : <strong>{source.title}</strong>}<span>{source.organization}</span><p>{source.note}</p></li>)}</ul></section>
    <div className="lesson-next"><div><p className="card-kicker">Ready to practice?</p><h2>Build the meaning yourself.</h2><p>Five questions about prefixes, roots, suffixes, routes, and the limits of word building.</p></div><ButtonLink to={`/lessons/${lesson.id}/quiz`}>Start knowledge check</ButtonLink></div>
  </article><aside className="lesson-sidebar" aria-label="Lesson contents"><p className="card-kicker">In this lesson</p><ol><li><a href="#word-parts"><span>01</span>Word parts</a></li><li><a href="#combining-vowels"><span>02</span>Combining vowels</a></li><li><a href="#prefixes"><span>03</span>Prefixes</a></li><li><a href="#roots"><span>04</span>Roots</a></li><li><a href="#suffixes"><span>05</span>Suffixes</a></li><li><a href="#svc-shorthand"><span>06</span>SVC shorthand</a></li><li><a href="#word-lab"><span>07</span>Word lab</a></li><li><a href="#limits"><span>08</span>Limits</a></li></ol><ButtonLink to={`/lessons/${lesson.id}/reference`} variant="quiet">Open reference card</ButtonLink></aside></div></div>
}
