export const medicalRecordLesson = {
  id: 'understanding-medical-records',
  courseId: 'medical-terminology',
  title: 'Understanding the Veterinary Medical Record',
  eyebrow: 'Medical Terminology · Lesson 2',
  summary: 'Learn the SOAP structure, SVC responsibility labels, and common record abbreviations used throughout the clinic.',
  estimatedMinutes: 20,
  riskLevel: 'Foundational',
  species: ['All-species terminology', 'SVC medical records'],
  reviewStatus: 'SVC SOP aligned',
  reviewedAt: 'August 15, 2026',
  reviewerRole: 'SVC SOP content alignment',
  status: 'approved',
  objectives: [
    'Identify the four sections of a SOAP record.',
    'Explain which SVC team member is responsible for each section.',
    'Distinguish client reports, direct observations, and veterinary assessments.',
    'Recognize common SVC intake abbreviations.',
    'Use None, Unknown, No info, and WNL accurately.',
    'Translate everyday client wording into clearer medical-record language.',
  ],
  sections: [
    { id: 'record-purpose', title: 'Why language matters' },
    { id: 'soap', title: 'SOAP' },
    { id: 'record-terms', title: 'Medical-record terms' },
    { id: 'abbreviations', title: 'SVC abbreviations' },
    { id: 'accuracy', title: 'Accuracy words' },
    { id: 'translations', title: 'Clinical translation' },
    { id: 'bella-soap', title: 'One patient across the SOAP' },
  ],
  recordPurpose: [
    'Why the patient was seen',
    'What the client reported',
    'What the veterinary team observed',
    'What the veterinarian determined',
    'What was recommended, performed, or declined',
    'What should happen next',
  ],
  soapSections: [
    {
      letter: 'S', title: 'Subjective', owner: '100% technician responsibility', tone: 'orange',
      question: 'What does the client report?',
      description: 'The Subjective records the client’s observations and the patient’s history, including the primary concern, timeline, EDUD, CSVD, diet, medications, lifestyle, previous conditions, seizures, and vaccine reactions.',
      cue: 'Subjective comes from the subject’s story—the history reported by the client.',
      clientWords: '“Bella threw up four times last night.”',
      recordWords: 'Owner reports approximately four episodes of vomiting since 10:00 p.m.',
      note: 'The technician did not witness the vomiting, so the statement remains attributed to the owner.',
    },
    {
      letter: 'O', title: 'Objective', owner: 'Veterinarian examination responsibility', tone: 'blue',
      question: 'What can be observed or measured?',
      description: 'The Objective contains information that can be seen, heard, counted, measured, felt, or assessed during the visit. At SVC, the veterinarian owns the physical examination. Technicians may add direct observations for veterinarian review according to clinic policy.',
      cue: 'Objective information comes from objects you can observe or measurements you can obtain.',
      clientWords: 'Patient appears to limp while walking down the hall.',
      recordWords: 'Patient is favoring the right hind leg while walking.',
      note: '“Patient has a torn ligament” would be an unsupported diagnosis—not an objective observation.',
    },
    {
      letter: 'A', title: 'Assessment', owner: 'Veterinarian responsibility', tone: 'blue',
      question: 'What does the veterinarian think is happening?',
      description: 'The Assessment communicates the veterinarian’s medical interpretation and how serious the condition may be. It may include a diagnosis, suspected diagnosis, differentials, and prognosis.',
      cue: 'The veterinarian assesses the evidence before naming the problem.',
      vocabulary: [
        ['Diagnosis', 'A confident identification supported by examination findings, test results, or other evidence.'],
        ['Suspected diagnosis', 'A condition considered likely but not definitively confirmed.'],
        ['Differentials', 'Possible explanations that have not yet been narrowed down to one diagnosis.'],
        ['Prognosis', 'The patient’s expected outcome.'],
      ],
    },
    {
      letter: 'P', title: 'Plan', owner: 'Shared technician and veterinarian responsibility', tone: 'neutral',
      question: 'What happens next?',
      description: 'The Plan records diagnostics, results, treatments, medications, client decisions, declined recommendations, instructions, communications, educational resources, and recheck plans.',
      cue: 'The Plan tells everyone what happens next.',
    },
  ],
  recordTerms: [
    { term: 'Signalment', definition: 'The patient’s species, breed, age, sex, and reproductive status.', example: 'Five-year-old spayed female Labrador retriever.' },
    { term: 'Chief complaint (CC)', definition: 'The client’s primary reason for bringing the patient to the clinic.', example: 'Vomiting, check lameness, vaccines, hair loss, or nail trim.' },
    { term: 'Client report', definition: 'Information provided by the client.', example: 'Owner reports… · Client states… · Per owner…' },
    { term: 'Direct observation', definition: 'Something a team member personally sees, hears, counts, or measures.', example: 'Patient walked into the room without assistance.' },
  ],
  abbreviations: [
    { term: 'TPR', means: 'Temperature · Pulse · Respiration', note: 'The core vital-sign abbreviation.' },
    { term: 'BCS', means: 'Body condition score', note: 'A standardized assessment of body condition.' },
    { term: 'MM', means: 'Mucous membranes', note: 'Often recorded with color and moisture.' },
    { term: 'CRT', means: 'Capillary refill time', note: 'A measured physical-examination finding.' },
    { term: 'UTD', means: 'Up to date', note: 'SVC requires the source: with SVC, with another clinic, or per owner.' },
    { term: 'EDUD', means: 'Eating · Drinking · Urination · Defecation', note: 'Record specific, measurable changes whenever possible.' },
    { term: 'CSVD', means: 'Coughing · Sneezing · Vomiting · Diarrhea', note: 'Describe presence, duration, frequency, and appearance.' },
    { term: 'WNL', means: 'Within normal limits', note: 'Use only when the information is truly normal.' },
  ],
  preventiveStatuses: [
    ['UTD with SVC', 'Preventive care can be confirmed in the SVC record.'],
    ['UTD with another clinic', 'SVC has records showing the dates and services performed elsewhere.'],
    ['UTD per owner', 'The client reports the patient is current, but SVC does not have supporting records.'],
    ['Due or overdue', 'The available information shows that the patient is not current.'],
  ],
  accuracyTerms: [
    { term: 'None', meaning: 'The client confirms that a symptom or history is not present.', example: 'No coughing, sneezing, vomiting, or diarrhea reported.' },
    { term: 'Unknown', meaning: 'The client or person in the room has not observed the information.', example: 'Defecation unknown; patient eliminates outside unsupervised.' },
    { term: 'No info', meaning: 'The client cannot provide the requested preventive-care details.', example: 'UTD per owner; vaccine names, clinic, and dates unavailable. No info.' },
    { term: 'WNL', meaning: 'The information has been confirmed to be within normal limits.', example: 'Eating, drinking, urination, and defecation reportedly WNL.' },
  ],
  translations: [
    {
      title: 'Lameness',
      client: '“He has been limping on his back right leg on and off.”',
      record: 'Owner reports intermittent right hind limb lameness.',
      map: [['on and off', 'intermittent'], ['back right leg', 'right hind limb'], ['limping', 'lameness'], ['client said it', 'owner reports']],
    },
    {
      title: 'Decreased appetite',
      client: '“She isn’t eating as much as usual.”',
      record: 'Owner reports patient has eaten approximately half of her normal amount for two days.',
      why: 'The revised note replaces a vague change with an estimated amount and duration.',
    },
    {
      title: 'Preventive status',
      client: '“I think all his shots are current.”',
      record: 'UTD per owner; no supporting records available. Owner is unsure which vaccines were administered or the dates of care.',
      why: 'The note preserves what the client believes while identifying what SVC cannot verify.',
    },
  ],
  bellaSoap: [
    ['Subjective · technician', 'Owner reports approximately four episodes of vomiting since 10:00 p.m. Bella reportedly vomited shortly after drinking water this morning and did not eat breakfast. Possible access to a child’s toy; ingestion was not witnessed.'],
    ['Objective · veterinarian examination', 'Direct observations, vital signs, and physical-examination findings are recorded here. Technicians may add observations for veterinarian review according to SVC policy.'],
    ['Assessment · veterinarian', 'The veterinarian records the diagnosis, suspected diagnosis, differentials, and prognosis.'],
    ['Plan · shared', 'The record lists diagnostics, treatments, client decisions, communications, instructions, and recheck recommendations.'],
  ],
  questions: [
    { id: 'q-subjective', concept: 'Subjective', prompt: 'The owner says their dog vomited three times overnight. Where does this belong?', options: ['Subjective', 'Objective', 'Assessment', 'Plan'], correctAnswer: 'Subjective', explanation: 'The information was reported by the owner, so it belongs in the Subjective history.' },
    { id: 'q-objective', concept: 'Objective description', prompt: 'A technician watches a patient favor its left hind leg while walking. Which wording is appropriate?', options: ['Patient has arthritis.', 'Patient tore a ligament.', 'Patient is favoring the left hind leg while walking.', 'Patient requires pain medication.'], correctAnswer: 'Patient is favoring the left hind leg while walking.', explanation: 'This records the direct observation without diagnosing the cause or recommending treatment.' },
    { id: 'q-assessment', concept: 'Assessment responsibility', prompt: 'Who is responsible for entering the diagnosis at SVC?', options: ['Client', 'Technician', 'Veterinarian', 'Receptionist'], correctAnswer: 'Veterinarian', explanation: 'The diagnosis belongs in the Assessment, which is the veterinarian’s responsibility.' },
    { id: 'q-unknown', concept: 'Accurate uncertainty', prompt: 'The client does not know whether their outdoor dog defecated today. Which word is most accurate?', options: ['None', 'Unknown', 'WNL', 'Normal'], correctAnswer: 'Unknown', explanation: 'The information was not observed. Unknown is more accurate than assuming the bowel movement was absent or normal.' },
    { id: 'q-edud', concept: 'EDUD', prompt: 'What does EDUD stand for?', options: ['Eating, drinking, urination, and defecation', 'Examination, diagnosis, updates, and discharge', 'Eating, digestion, urinalysis, and diet', 'Examination details under diagnosis'], correctAnswer: 'Eating, drinking, urination, and defecation', explanation: 'EDUD organizes four routine history areas: eating, drinking, urination, and defecation.' },
  ],
  referenceGroups: [
    { title: 'SOAP', items: ['S · Subjective · client-reported history', 'O · Objective · observations, measurements, and examination', 'A · Assessment · veterinarian’s medical interpretation', 'P · Plan · what happens next'] },
    { title: 'SVC responsibilities', items: ['Technician: Concerns & Questions, Vitals, Subjective', 'Veterinarian: physical examination and Assessment', 'Shared: Plan documentation'] },
    { title: 'Abbreviations', items: ['CC · chief complaint', 'TPR · temperature, pulse, respiration', 'BCS · body condition score', 'MM · mucous membranes', 'CRT · capillary refill time', 'UTD · up to date', 'EDUD · eating, drinking, urination, defecation', 'CSVD · coughing, sneezing, vomiting, diarrhea', 'WNL · within normal limits'] },
    { title: 'Accuracy words', items: ['None · confirmed absent', 'Unknown · not observed', 'No info · requested details unavailable', 'WNL · confirmed within normal limits'] },
  ],
  sources: [
    { title: 'Medical Records (SOAPS) SOP', organization: 'SVC', note: 'Clinic-specific SOAP responsibilities, abbreviations, documentation language, and preventive-status distinctions.' },
    { title: '2023 AAHA Technician Utilization Guidelines', organization: 'American Animal Hospital Association', url: 'https://www.aaha.org/resources/2023-aaha-technician-utilization-guidelines/standardized-workflow-for-optimal-utilization-table-5-2/', note: 'Supports team-based history collection, initial assessment, and case presentation.' },
    { title: 'Model Documents: Scope of Practice', organization: 'American Association of Veterinary State Boards', url: 'https://www.aavsb.org/board-services/member-board-resources/practice-act-model/', note: 'Responsibilities remain subject to credentials, supervision, and jurisdiction.' },
  ],
}
