export const radiographLesson = {
  id: 'radiograph-projection-terminology',
  courseId: 'medical-terminology',
  title: 'Radiograph & Projection Terminology',
  eyebrow: 'Medical Terminology · Lesson 5',
  summary: 'Learn the language used to name projections, describe image quality, and communicate radiographic observations clearly.',
  estimatedMinutes: 24,
  riskLevel: 'Radiation safety',
  species: ['Dogs, cats, horses & livestock', 'General radiographic language'],
  reviewStatus: 'Source verified',
  reviewedAt: 'August 16, 2026',
  reviewerRole: 'Editorial, terminology, and radiation-safety review',
  status: 'approved',
  objectives: [
    'Distinguish an x-ray, a radiograph, radiography, position, and projection.',
    'Use beam-entry and beam-exit language to interpret common projection names.',
    'Recognize common lateral, DV, VD, CrCd, CdCr, and oblique projections.',
    'Describe image appearance and technical quality without making a diagnosis.',
    'Use ALARA and other radiation-safety terms correctly while following clinic protocols.',
  ],
  sections: [
    { id: 'core-language', title: 'Core language' },
    { id: 'position-projection', title: 'Position vs projection' },
    { id: 'common-projections', title: 'Common projections' },
    { id: 'appearance', title: 'Image appearance' },
    { id: 'quality', title: 'Image quality' },
    { id: 'handoff', title: 'Clear handoff' },
    { id: 'safety', title: 'Safety language' },
  ],
  coreTerms: [
    { term: 'X-ray', meaning: 'The ionizing radiation used to create the image.', cue: 'The x-ray passes through the patient.' },
    { term: 'Radiograph', meaning: 'The image produced by the radiographic exposure.', cue: 'You review a radiograph.' },
    { term: 'Radiography', meaning: 'The process of producing radiographs.', cue: 'Radiography describes the procedure or imaging method.' },
  ],
  projectionTerms: [
    { term: 'Position', meaning: 'How the patient is placed, such as dorsal, sternal, or lateral recumbency.' },
    { term: 'Projection', meaning: 'The path of the primary beam through the patient, named from the surface where it enters to the surface where it exits.' },
    { term: 'View', meaning: 'Common conversational wording for an image or projection. Projection is the more precise term when naming beam direction.' },
    { term: 'Recumbency', meaning: 'A lying position. The named side identifies the surface supporting the patient.' },
    { term: 'Orthogonal', meaning: 'Two projections made approximately 90 degrees apart to show anatomy in different planes.' },
    { term: 'Oblique', meaning: 'An intentionally angled projection used to separate structures that overlap on standard projections.' },
  ],
  projections: [
    { abbreviation: 'DV', term: 'Dorsoventral', beam: 'Enters the dorsal surface and exits the ventral surface.', position: 'The patient is commonly in sternal recumbency.' },
    { abbreviation: 'VD', term: 'Ventrodorsal', beam: 'Enters the ventral surface and exits the dorsal surface.', position: 'The patient is in dorsal recumbency.' },
    { abbreviation: 'Right lateral', term: 'Right lateral projection', beam: 'The beam travels from the patient’s left side toward the right side.', position: 'The patient’s right side is closest to the detector.' },
    { abbreviation: 'Left lateral', term: 'Left lateral projection', beam: 'The beam travels from the patient’s right side toward the left side.', position: 'The patient’s left side is closest to the detector.' },
    { abbreviation: 'CrCd', term: 'Craniocaudal', beam: 'Enters the cranial surface and exits the caudal surface.', position: 'Used when cranial and caudal correctly name the surfaces of the region.' },
    { abbreviation: 'CdCr', term: 'Caudocranial', beam: 'Enters the caudal surface and exits the cranial surface.', position: 'The reverse beam path of a CrCd projection.' },
  ],
  projectionExamples: [
    {
      abbreviation: 'DV',
      term: 'Dorsoventral thorax',
      image: '/radiography/dv-thorax.png',
      alt: 'Dorsoventral thoracic radiograph of a dog with a left-side marker.',
      patientPosition: 'Patient lies on the chest/belly in sternal recumbency. The front legs are extended toward the head and slightly away from the chest. The hind legs rest in a comfortable, natural position. The head is supported so the sternum and spine remain straight and aligned.',
      beam: 'Dorsal → ventral',
      position: 'Dorsoventral means the beam enters through the dorsal surface—the back—and exits through the ventral surface—the chest.',
      marker: 'The L marker identifies the patient’s left side.',
      source: 'Veterinary Key',
      sourceUrl: 'https://veteriankey.com/',
      sourceSlide: 6,
    },
    {
      abbreviation: 'VD',
      term: 'Ventrodorsal thorax',
      image: '/radiography/vd-thorax.png',
      alt: 'Ventrodorsal thoracic radiograph of a dog with a left-side marker.',
      patientPosition: 'Patient lies on the back in dorsal recumbency, usually supported in a V-trough. The head and neck are kept straight, and the front legs are extended toward the head. The hind legs are positioned comfortably and secured so the sternum and spine remain aligned.',
      beam: 'Ventral → dorsal',
      position: 'Ventrodorsal means the beam enters through the ventral surface—the chest—and exits through the dorsal surface—the back.',
      marker: 'When displayed using SVC orientation, the L marker appears on the viewer’s right.',
      source: 'Veterinary Key',
      sourceUrl: 'https://veteriankey.com/',
      sourceSlide: 5,
    },
    {
      abbreviation: 'Right lateral',
      term: 'Right lateral abdomen',
      image: '/radiography/right-lateral-abdomen.png',
      alt: 'Right lateral abdominal radiograph of a dog with an R marker.',
      patientPosition: 'Patient lies on the right side. The front legs are extended toward the head, and the hind legs are extended toward the tail so they do not overlap the abdomen. The head and neck remain aligned with the spine, and the hips are positioned without rotation.',
      beam: 'Left → right',
      position: 'A lateral projection is named for the side closest to the detector. Here, that side is the right side.',
      marker: 'The R marker confirms the right side was down on the table.',
      source: 'Antech Imaging Services',
      sourceUrl: 'https://antechimagingservices.com/',
      sourceSlide: 8,
    },
    {
      abbreviation: 'Left lateral',
      term: 'Left lateral thorax',
      image: '/radiography/left-lateral-thorax.png',
      alt: 'Left lateral thoracic radiograph of a dog with an L marker.',
      patientPosition: 'Patient lies on the left side. The front legs are extended toward the head to move the shoulders away from the chest. The hind legs are extended toward the tail, and the head and neck remain aligned with the spine. The sternum may be supported to prevent rotation.',
      beam: 'Right → left',
      position: 'A lateral projection is named for the side closest to the detector. Here, that side is the left side.',
      marker: 'The L marker confirms the left side was down on the table.',
      source: 'Veterinary Key',
      sourceUrl: 'https://veteriankey.com/',
      sourceSlide: 4,
    },
    {
      abbreviation: 'CrCd',
      term: 'Craniocaudal elbow',
      image: '/radiography/crcd-elbow.png',
      alt: 'Craniocaudal radiograph of a dog’s right elbow.',
      patientPosition: 'Patient lies on the chest/belly in ventral recumbency. The affected front leg is extended toward the head and centered over the detector. The unaffected leg and head are positioned away from the elbow being imaged. At SVC, the head may be elevated as needed to help straighten the humerus.',
      beam: 'Cranial → caudal',
      position: 'Craniocaudal means the beam enters the cranial—or front—surface of the elbow and exits through the caudal—or back—surface.',
      marker: 'The R marker identifies the right limb.',
      source: 'Today’s Veterinary Nurse',
      sourceUrl: 'https://todaysveterinarynurse.com/',
      sourceSlide: 18,
    },
    {
      abbreviation: 'CdCr',
      term: 'Caudocranial tibia/fibula',
      image: '/radiography/cdcr-tibia-fibula.png',
      alt: 'Caudocranial radiograph of a dog’s right tibia and fibula.',
      patientPosition: 'Patient lies on the chest/belly in ventral recumbency. The affected hind leg is extended toward the tail with the tibia and fibula straight and centered over the detector. The opposite hind leg is flexed or moved aside, and the pelvis is supported to prevent rotation.',
      beam: 'Caudal → cranial',
      position: 'Caudocranial means the beam enters the caudal—or back—surface of the limb and exits through the cranial—or front—surface.',
      marker: 'The R marker identifies the right limb; proximal anatomy is displayed at the top.',
      source: 'University of Illinois College of Veterinary Medicine',
      sourceUrl: 'https://vetmed.illinois.edu/',
      sourceSlide: 41,
    },
  ],
  positioningSafetyRule: 'Use sedation and positioning aids whenever appropriate. Staff should step behind the protective barrier before exposure whenever possible. If manual restraint is unavoidable, follow clinic policy, wear all required protective equipment, and keep every part of the handler’s body outside the primary beam.',
  clinicOrientationRules: [
    { label: 'Lateral images', text: 'Use the R or L marker for the side that was down on the table. Display the patient’s head toward the left.' },
    { label: 'VD and DV images', text: 'Place the patient’s right side on the viewer’s left, or the left side on the viewer’s right.' },
    { label: 'Long bones and joints', text: 'Display proximal anatomy at the top and distal anatomy at the bottom. The marker identifies the correct limb.' },
  ],
  clinicStudyPattern: 'At SVC, a pulmonary thorax study uses right lateral, left lateral, and VD projections. A cardiac thorax study adds a DV projection.',
  densities: [
    { name: 'Gas', appearance: 'Darkest', explanation: 'Allows more x-rays to reach the detector.' },
    { name: 'Fat', appearance: 'Dark gray', explanation: 'Slightly more opaque than gas.' },
    { name: 'Soft tissue / fluid', appearance: 'Medium gray', explanation: 'Soft tissue and fluid have similar radiographic opacity.' },
    { name: 'Mineral', appearance: 'Light gray to white', explanation: 'Bone and mineral attenuate more of the beam.' },
    { name: 'Metal', appearance: 'Brightest white', explanation: 'Strongly attenuates the x-ray beam.' },
  ],
  appearanceTerms: [
    { term: 'Radiopaque', meaning: 'Relatively white or light because fewer x-rays reach the detector.' },
    { term: 'Radiolucent', meaning: 'Relatively dark because more x-rays reach the detector.' },
    { term: 'Opacity', meaning: 'A structure’s relative radiographic whiteness or ability to attenuate the beam.' },
    { term: 'Superimposition', meaning: 'Structures overlap because a radiograph compresses three-dimensional anatomy into a two-dimensional image.' },
  ],
  qualityTerms: [
    { term: 'Rotation', meaning: 'Unintended patient turning that creates asymmetry. An intentional oblique projection is not the same as accidental rotation.' },
    { term: 'Motion artifact', meaning: 'Blur or doubled edges caused by movement during the exposure.' },
    { term: 'Collimation', meaning: 'Restricting the x-ray field to the anatomy needed for the study.' },
    { term: 'Anatomical marker', meaning: 'A radiopaque marker identifying patient side or other required information according to clinic protocol.' },
    { term: 'Exposure', meaning: 'The production of the image using selected technique factors. In digital radiography, screen brightness alone does not reliably show detector exposure.' },
    { term: 'Artifact', meaning: 'A feature on the image that does not represent the patient’s anatomy.' },
  ],
  handoffs: [
    { everyday: '“The dog moved and the chest image looks blurry.”', clinical: 'Motion artifact is present on the lateral thoracic radiograph.', why: 'Names the technical issue and the affected projection without interpreting disease.' },
    { everyday: '“The dog looks crooked in this image.”', clinical: 'Rotation is present on the VD thoracic radiograph.', why: 'Describes positioning quality. It does not call an intentional oblique projection an error.' },
    { everyday: '“There is a very white object over the abdomen.”', clinical: 'Radiopaque material projects over the abdomen.', why: 'Describes appearance and location. The veterinarian determines what the material represents.' },
  ],
  safetyTerms: [
    { term: 'ALARA', meaning: 'As Low As Reasonably Achievable: minimize radiation exposure while obtaining the image quality required for the clinical purpose.' },
    { term: 'Dosimeter', meaning: 'A device worn according to workplace protocol to monitor occupational radiation exposure.' },
    { term: 'Collimation', meaning: 'Limits the exposed field and helps reduce unnecessary patient exposure and scatter radiation.' },
    { term: 'Positioning aids', meaning: 'Tools used under clinic protocol to support positioning and reduce the need for manual restraint.' },
  ],
  safetyRule: 'Radiographic positioning and exposure require training, veterinary direction, clinic protocols, and applicable radiation-safety laws. Never improvise a restraint or exposure technique from this terminology lesson.',
  questions: [
    { id: 'q-radiograph', concept: 'Core terminology', prompt: 'Which term names the image produced after an x-ray exposure?', options: ['Radiograph', 'Radiography', 'Projection', 'Collimation'], correctAnswer: 'Radiograph', explanation: 'An x-ray is the radiation, a radiograph is the resulting image, and radiography is the process used to produce it.' },
    { id: 'q-dv', concept: 'Projection naming', prompt: 'In a dorsoventral (DV) projection, where does the primary beam enter and exit?', options: ['Enters dorsal and exits ventral', 'Enters ventral and exits dorsal', 'Enters right and exits left', 'Enters caudal and exits cranial'], correctAnswer: 'Enters dorsal and exits ventral', explanation: 'Projection names follow the beam from the entry surface to the exit surface.' },
    { id: 'q-lateral', concept: 'Lateral projections', prompt: 'For a right lateral projection, which side of the patient is closest to the detector?', options: ['Right side', 'Left side', 'Dorsal surface', 'Ventral surface'], correctAnswer: 'Right side', explanation: 'The patient is in right lateral recumbency, with the right side closest to the detector.' },
    { id: 'q-motion', concept: 'Image quality', prompt: 'Which term describes blurred or doubled edges caused by movement during an exposure?', options: ['Motion artifact', 'Radiopacity', 'Collimation', 'Orthogonal projection'], correctAnswer: 'Motion artifact', explanation: 'Movement during the exposure can produce blur or doubled edges called motion artifact.' },
    { id: 'q-description', concept: 'Objective communication', prompt: 'Which statement objectively describes an image without making a diagnosis?', options: ['Radiopaque material projects over the abdomen.', 'The patient swallowed a metal foreign body.', 'This is definitely an intestinal obstruction.', 'The opacity is causing abdominal pain.'], correctAnswer: 'Radiopaque material projects over the abdomen.', explanation: 'The statement describes visible opacity and location. Identifying the material or diagnosing its significance requires veterinary interpretation.' },
  ],
  referenceGroups: [
    { title: 'Image and process', items: ['X-ray · ionizing radiation used to create the image', 'Radiograph · the resulting image', 'Radiography · the process of producing radiographs'] },
    { title: 'Projection language', items: ['Projection · beam entry to beam exit', 'Position · how the patient is placed', 'Recumbency · a lying position', 'Orthogonal · projections about 90° apart', 'Oblique · intentionally angled projection'] },
    { title: 'Common projections', items: ['DV · dorsal to ventral', 'VD · ventral to dorsal', 'Right lateral · right side nearest detector', 'Left lateral · left side nearest detector', 'CrCd · cranial to caudal', 'CdCr · caudal to cranial'] },
    { title: 'Appearance and quality', items: ['Radiopaque · relatively white', 'Radiolucent · relatively dark', 'Motion artifact · movement-related blur', 'Rotation · unintended asymmetry', 'Collimation · restrict the x-ray field', 'Artifact · not patient anatomy'] },
    { title: 'Safety language', items: ['ALARA · As Low As Reasonably Achievable', 'Dosimeter · monitors occupational exposure', 'Positioning aids · support protocol-directed positioning', 'Follow clinic protocols and applicable laws'] },
  ],
  sources: [
    { title: 'Complete Radiograph Positioning Guide', organization: 'SVC training presentation', note: 'Clinic positioning, marker orientation, projection examples, and radiograph source credits used in this lesson.' },
    { title: 'Radiography of Animals', organization: 'Merck Veterinary Manual', url: 'https://www.merckvetmanual.com/clinical-pathology-and-procedures/diagnostic-imaging/radiography-of-animals', note: 'Supports projection selection, patient positioning, collimation, orthogonal studies, and common technical-quality terminology.' },
    { title: 'Nomina Anatomica Veterinaria, Sixth Edition', organization: 'World Association of Veterinary Anatomists', url: 'https://wava-amav.org/wava-documents.html', note: 'Standard veterinary directional terminology used to construct projection names.' },
    { title: 'Medical X-ray Imaging', organization: 'U.S. Food and Drug Administration', url: 'https://www.fda.gov/radiation-emitting-products/medical-imaging/medical-x-ray-imaging', note: 'Supports ALARA, appropriate training, technique optimization, and radiation-safety terminology.' },
    { title: 'Small Animal Thoracic Radiography', organization: 'Today’s Veterinary Practice', url: 'https://todaysveterinarypractice.com/radiology-imaging/small-animal-thoracic-radiography/', note: 'Supports patient alignment and limb positioning for lateral, VD, and DV thoracic projections.' },
    { title: 'Small Animal Abdominal Radiography', organization: 'Today’s Veterinary Practice', url: 'https://todaysveterinarypractice.com/radiology-imaging/small-animal-abdominal-radiography/', note: 'Supports limb placement, laterality, and rotation control for lateral abdominal projections.' },
    { title: 'Small Animal Elbow and Antebrachium Radiography', organization: 'Today’s Veterinary Practice', url: 'https://todaysveterinarypractice.com/radiology-imaging/imaging-essentials-small-animal-elbow-and-antebrachium-radiography/', note: 'Supports ventral recumbency and affected-limb positioning for the craniocaudal elbow projection.' },
    { title: 'Small Animal Radiography: Stifle Joint and Crus', organization: 'Today’s Veterinary Practice', url: 'https://todaysveterinarypractice.com/radiology-imaging/small-animal-radiography-stifle-joint-and-crus/', note: 'Supports ventral recumbency and caudal limb extension for caudocranial tibia and fibula positioning.' },
    { title: 'Hands-free Radiology: Benefits and Best Practices', organization: 'American Animal Hospital Association', url: 'https://www.aaha.org/trends-magazine/publications/hands-free-radiology-benefits-and-best-practices/', note: 'Supports sedation, positioning aids, and reducing manual restraint during radiographic exposure.' },
  ],
}
