export const wordBuildingLesson = {
  id: 'building-medical-words',
  courseId: 'medical-terminology',
  title: 'Building Medical Words',
  eyebrow: 'Medical Terminology · Lesson 3',
  summary: 'Break unfamiliar medical terms into smaller pieces you can recognize, translate, and use in the clinic.',
  estimatedMinutes: 22,
  riskLevel: 'Foundational',
  species: ['Dogs, cats & livestock', 'SVC terminology'],
  reviewStatus: 'Source verified',
  reviewedAt: 'August 15, 2026',
  reviewerRole: 'Editorial and source review',
  status: 'approved',
  objectives: [
    'Identify a prefix, root, and suffix.',
    'Recognize common word parts used in veterinary medicine.',
    'Translate an unfamiliar term into everyday language.',
    'Connect selected SVC abbreviations with their full medical terms.',
    'Recognize when a word breakdown does not provide the complete clinical meaning.',
  ],
  sections: [
    { id: 'word-parts', title: 'Parts of a medical word' },
    { id: 'combining-vowels', title: 'Combining vowels' },
    { id: 'prefixes', title: 'Common prefixes' },
    { id: 'roots', title: 'Common roots' },
    { id: 'suffixes', title: 'Common suffixes' },
    { id: 'svc-shorthand', title: 'Inside SVC shorthand' },
    { id: 'word-lab', title: 'Build the meaning' },
    { id: 'limits', title: 'Clues, not diagnoses' },
  ],
  wordParts: [
    { name: 'Prefix', position: 'Beginning', description: 'May describe location, amount, direction, or speed.', example: 'hyper- means excessive or above normal.' },
    { name: 'Root', position: 'Core', description: 'Usually identifies a body part, organ, or system.', example: 'cardi means heart.' },
    { name: 'Suffix', position: 'Ending', description: 'Often identifies a condition, procedure, or state.', example: '-itis means inflammation.' },
  ],
  prefixPairs: [
    {
      title: 'Hyper- and hypo-',
      terms: [
        { term: 'hyper-', meaning: 'Excessive, above normal, or high', cue: 'Someone who is hyper has an unusually high amount of energy.', example: 'hyper + glyc + emia = hyperglycemia' },
        { term: 'hypo-', meaning: 'Below normal, deficient, or low', cue: 'Hypo goes below.', example: 'hypo + glyc + emia = hypoglycemia' },
      ],
      scenario: 'A weak puppy has a low blood glucose measurement.',
      wording: 'The puppy is hypoglycemic.',
      pronunciation: 'high-poh-gly-SEE-mik',
      contrast: 'The glucose measurement is below normal, so the term begins with hypo-. If it were above normal, the correct term would be hyperglycemic.',
    },
    {
      title: 'Tachy- and brady-',
      terms: [
        { term: 'tachy-', meaning: 'Fast or abnormally rapid', cue: 'A tachometer measures how fast an engine is running.', example: 'tachy + pnea = tachypnea' },
        { term: 'brady-', meaning: 'Slow or abnormally reduced in speed', cue: 'Brakes slow something down.', example: 'brady + pnea = bradypnea' },
      ],
      scenario: 'A cat’s respiratory rate is above the expected range for its current condition.',
      wording: 'Tachypnea is present.',
      breakdown: [['tachy-', 'abnormally fast'], ['-pnea', 'breathing']],
      translation: 'Abnormally rapid breathing.',
      pronunciation: 'tack-ip-NEE-uh',
      alternative: { term: 'Bradypnea', meaning: 'Abnormally slow breathing.', pronunciation: 'brad-ip-NEE-uh' },
      contrast: 'The breathing rate is abnormally rapid, so the term begins with tachy-. If it were abnormally slow, the term would be bradypnea.',
    },
    {
      title: 'Poly- and oligo-',
      terms: [
        { term: 'poly-', meaning: 'Many, much, or excessive', cue: 'A polygon can have many sides.', example: 'poly + uria = polyuria' },
        { term: 'oligo-', meaning: 'Few, little, or decreased', cue: 'Oligo means only a little.', example: 'oligo + uria = oliguria' },
      ],
      scenario: 'A dog is producing a larger volume of urine than expected.',
      wording: 'The owner reports polyuria.',
      pronunciation: 'pol-ee-YOOR-ee-uh',
      alternative: { term: 'Oliguria', meaning: 'Abnormally decreased urine production.', pronunciation: 'ol-ih-GYOOR-ee-uh' },
      contrast: 'The amount of urine produced has increased, so the term begins with poly-. If the dog were producing an abnormally small amount, the term would be oliguria.',
      note: 'Polyuria describes increased urine volume. It does not simply mean the patient is attempting to urinate frequently.',
    },
  ],
  otherPrefixes: [
    ['a- or an-', 'Without or absent', 'Absent', 'Apnea'],
    ['dys-', 'Difficult, painful, or abnormal', 'Dysfunctional means not working normally', 'Dyspnea (disp-NEE-uh)'],
    ['peri-', 'Around', 'A perimeter goes around an area', 'Periocular (pair-ee-OK-yuh-ler)'],
    ['intra-', 'Within or inside', 'Intramural activities happen within one school', 'Intramuscular'],
    ['sub-', 'Under or below', 'A submarine travels under water', 'Subcutaneous'],
  ],
  roots: [
    ['cardi', 'Heart', 'Cardiology'], ['derm or dermat', 'Skin', 'Dermatitis'], ['gastr', 'Stomach', 'Gastritis'],
    ['enter', 'Intestine', 'Enteritis'], ['hepat', 'Liver', 'Hepatomegaly'], ['nephr', 'Kidney', 'Nephrectomy'],
    ['oste', 'Bone', 'Osteotomy'], ['arthr', 'Joint', 'Arthritis'], ['my or myo', 'Muscle', 'Myopathy'],
    ['neur', 'Nerve', 'Neurology'], ['hemat or hem', 'Blood', 'Hematology'], ['ot', 'Ear', 'Otitis'],
    ['ophthalm or ocul', 'Eye', 'Ophthalmology'], ['rhin or nas', 'Nose', 'Intranasal'], ['ven', 'Vein', 'Intravenous'],
  ],
  suffixGroups: [
    { title: 'Conditions and findings', items: [['-itis', 'Inflammation', 'Dermatitis'], ['-osis', 'Condition or abnormal state', 'Dermatosis'], ['-emia', 'Blood condition', 'Hypoglycemia'], ['-uria', 'Urine condition', 'Polyuria'], ['-pnea', 'Breathing', 'Tachypnea'], ['-megaly', 'Enlargement', 'Hepatomegaly'], ['-pathy', 'Disease', 'Myopathy'], ['-algia', 'Pain', 'Arthralgia'], ['-penia', 'Deficiency or decreased amount', 'Leukopenia']] },
    { title: 'Procedures', items: [['-ectomy', 'Surgical removal', 'Nephrectomy'], ['-otomy', 'Incision into or cutting into', 'Osteotomy'], ['-scopy', 'Visual examination using an instrument', 'Endoscopy'], ['-stomy', 'Creation of an opening', 'Colostomy']] },
    { title: 'Pertaining to', items: [['-ac', 'Pertaining to', 'Cardiac'], ['-al', 'Pertaining to', 'Nasal'], ['-ar', 'Pertaining to', 'Muscular'], ['-ous', 'Pertaining to', 'Intravenous']] },
  ],
  svcRoutes: [
    { abbreviation: 'IV', term: 'Intravenous', pieces: [['intra-', 'within'], ['ven', 'vein'], ['-ous', 'pertaining to']], translation: 'Pertaining to or occurring within a vein.' },
    { abbreviation: 'IM', term: 'Intramuscular', pieces: [['intra-', 'within'], ['muscul', 'muscle'], ['-ar', 'pertaining to']], translation: 'Pertaining to or occurring within a muscle.' },
    { abbreviation: 'IN', term: 'Intranasal', pieces: [['intra-', 'within'], ['nas', 'nose'], ['-al', 'pertaining to']], translation: 'Pertaining to or occurring within the nose.' },
    { abbreviation: 'IC', term: 'Intracardiac', pieces: [['intra-', 'within'], ['cardi', 'heart'], ['-ac', 'pertaining to']], translation: 'Pertaining to or occurring within the heart.' },
    { abbreviation: 'SC or SQ', term: 'Subcutaneous', pronunciation: 'sub-kyoo-TAY-nee-us', pieces: [['sub-', 'under'], ['cutane', 'skin'], ['-ous', 'pertaining to']], translation: 'Pertaining to or occurring under the skin.' },
  ],
  wordLab: [
    { term: 'Gastroenteritis', pronunciation: 'gas-troh-en-tuh-RYE-tis', pieces: [['gastr', 'stomach'], ['enter', 'intestine'], ['-itis', 'inflammation']], translation: 'Inflammation of the stomach and intestines.', example: 'A goat is presented for vomiting and diarrhea. Those observations alone do not prove the patient has gastroenteritis; the veterinarian determines whether that diagnosis is appropriate.' },
    { term: 'Hepatomegaly', pronunciation: 'hep-uh-toh-MEG-uh-lee', pieces: [['hepat', 'liver'], ['-megaly', 'enlargement']], translation: 'Enlargement of the liver.', example: 'A veterinarian identifies an enlarged liver during diagnostic imaging. The term describes the finding, but it does not explain why the liver is enlarged.' },
    { term: 'Dermatitis', pieces: [['dermat', 'skin'], ['-itis', 'inflammation']], translation: 'Inflammation of the skin.', example: 'Red, irritated skin can be documented objectively. Dermatitis should be used as a diagnosis only when supported by the veterinarian’s assessment.' },
    { term: 'Nephrectomy', pronunciation: 'neh-FREK-tuh-mee', pieces: [['nephr', 'kidney'], ['-ectomy', 'surgical removal']], translation: 'Surgical removal of a kidney.', contrast: 'A nephrectomy removes a kidney. A nephrotomy is an incision into a kidney without necessarily removing it.' },
    { term: 'Ovariohysterectomy · OHE', pronunciation: 'oh-vair-ee-oh-hiss-ter-EK-tuh-mee', pieces: [['ovari', 'ovary'], ['hyster', 'uterus'], ['-ectomy', 'surgical removal']], translation: 'Surgical removal of the ovaries and uterus.', example: 'SVC may abbreviate the procedure as OHE. The abbreviation is shorthand for the procedure—not a separate medical term.' },
  ],
  limitations: [
    'Polyuria means increased urine production, not simply frequent trips outside.',
    'Osteoarthritis contains word parts for bone, joint, and inflammation, but those pieces do not explain the disease’s complete process.',
    'A word ending in -oma identifies a mass or tumor, but the ending alone does not tell you whether it is benign or malignant.',
    'Similar abbreviations may mean different things in different clinics.',
  ],
  questions: [
    { id: 'q-hypo', concept: 'Prefixes', prompt: 'Which part of hypoglycemia means low or below normal?', options: ['hypo-', 'glyc', '-emia'], correctAnswer: 'hypo-', explanation: 'The prefix hypo- means below normal, deficient, or low.' },
    { id: 'q-dermatitis', concept: 'Word roots and suffixes', prompt: 'What does dermatitis describe?', options: ['Surgical removal of skin', 'Inflammation of the skin', 'Enlargement of the skin'], correctAnswer: 'Inflammation of the skin', explanation: 'Dermat means skin and -itis means inflammation.' },
    { id: 'q-route', concept: 'Medication-route terms', prompt: 'A medication is administered beneath the skin. Which route term fits?', options: ['Intramuscular', 'Subcutaneous', 'Intranasal'], correctAnswer: 'Subcutaneous', explanation: 'Sub- means under and cutane refers to skin.' },
    { id: 'q-ectomy', concept: 'Procedure suffixes', prompt: 'Which suffix means surgical removal?', options: ['-itis', '-otomy', '-ectomy'], correctAnswer: '-ectomy', explanation: 'The suffix -ectomy means surgical removal. The suffix -otomy means an incision into a structure.' },
    { id: 'q-limits', concept: 'Limits of word building', prompt: 'Why can’t word parts alone confirm a diagnosis?', options: ['They only provide a general meaning without the patient’s clinical evidence.', 'They are used only for medications.', 'They never identify a body part.'], correctAnswer: 'They only provide a general meaning without the patient’s clinical evidence.', explanation: 'Word parts provide clues, but diagnosis also requires examination findings, test results, clinical context, and veterinary assessment.' },
  ],
  referenceGroups: [
    { title: 'Prefixes', items: ['hyper- · high or excessive', 'hypo- · low or deficient', 'tachy- · fast', 'brady- · slow', 'poly- · many or excessive', 'oligo- · few or little', 'a- or an- · without', 'dys- · difficult or abnormal', 'peri- · around', 'intra- · within', 'sub- · under'] },
    { title: 'Suffixes', items: ['-itis · inflammation', '-osis · condition', '-emia · blood condition', '-uria · urine condition', '-pnea · breathing', '-megaly · enlargement', '-pathy · disease', '-algia · pain', '-penia · deficiency', '-ectomy · surgical removal', '-otomy · incision into', '-scopy · visual examination'] },
    { title: 'SVC routes', items: ['IV · intravenous', 'IM · intramuscular', 'IN · intranasal', 'IC · intracardiac', 'SC or SQ · subcutaneous'] },
    { title: 'Word-building reminders', items: ['Prefix · beginning', 'Root · core meaning', 'Suffix · ending', 'Combining vowel · usually o', 'Not every term has all three parts', 'Word parts provide clues—not a diagnosis'] },
  ],
  sources: [
    { title: 'Understanding Medical Words: Break It Up', organization: 'National Library of Medicine', url: 'https://medlineplus.gov/medwords/breakitup1.html', note: 'Introduces prefixes, roots, suffixes, and the structure of medical words.' },
    { title: 'Appendix A: Word Parts and What They Mean', organization: 'National Library of Medicine', url: 'https://medlineplus.gov/appendixa.html', note: 'Reference for common medical prefixes, roots, and suffixes.' },
    { title: 'Common Abbreviations', organization: 'SVC', note: 'Clinic-specific medication routes and procedure abbreviations used as applied examples.' },
  ],
}
